var SellerID=0,sellerType=0,avlID=0,ClientID=0,ClentList=[],AvlClientList=[],AvlList=[],SocAvlList=[],PAGE_CLIENT_MAIN=0,PAGE_AGENTMAIN=1,PageType=PAGE_CLIENT_MAIN,SocietyDetail=[],FavList=[];$(window).resize(Resized);function Resized(){var g=$(window).height();$(window).width();g-=80;$("#divInstruction").height(g-20)}
$(document).ready(function(){$("#tableFloorPlans input").bind("keyup",function(){CalculatePrice($(this).attr("id").split("_")[1])});PageType==PAGE_AGENTMAIN&&GetAvlList(SellerID);$("#txtFilter").keyup(function(){var h=$("#txtFilter").val().toLowerCase(),e=[];$(ClentList).each(function(){this.Name!=undefined&&this.Name.toLowerCase().indexOf(h)>-1&&e.push(this)});ShowClientList(e)});try{$(".fancybox").fancybox({});$(".fancyBox").fancybox({titleShow:"true",transitionIn:"elastic",transitionOut:"elastic",
speedIn:600,speedOut:200,overlayShow:true,helpers:{title:{type:"outside",position:"top"}}});$(".manualfancybox").click(function(){var h=[];$(".details_gallery_min a").each(function(){href=$(this).attr("href");title=$(this).attr("title");h.push({href:href,title:title})});jQuery.fancybox(h,{transitionIn:"elastic",easingIn:"easeOutBack",transitionOut:"elastic",easingOut:"easeInBack",opacity:false,titleShow:true,titlePosition:"over",type:"image",titleFromAlt:true})})}catch(g){}$("#hidSubCity").val();
Resized()});function GetSocietyListDone(g){$("#divSociety").html(ShowError(g)[1]);$("#societytable").HighLightRows();$("#societytable a").css("text-decoration","none");$("#societytable th").addClass("tablehead")}
function GetSocietyAvailability(g,h){$.ajax({url:"Data.aspx?Action=GetAvailibilityText&Data4=1&Data1="+g+"&Data2="+h,cache:false,success:function(e){e=ShowError2(e);SocAvlList.length=0;$(e).each(function(){SocAvlList.push({ID:this[0],SocietyID:this[1],SocietyName:this[2],SellerID:this[3],SellerName:this[4],BHK:this[5],Amount:this[6],AvailableFrom:this[7],Area:this[8],Bathroom:this[9],FloorNo:this[10],Facing:this[11],PostedOnDate:this[12]})});ShowList(SocAvlList)}})}
function ShowList(g){var h=1,e="<table style='border-spacing:1px;'><tr><th></th><th>Society</th><th>BHK</th><th>Rent</th><th>Area</th><th>Bath</th><th>Floor</th><th>Featutres</th><th>Avl From</th><th>Posted Bef(days)</th></tr>";$(g).each(function(){if(this.ID!=undefined){e+="<tr onclick='ShowAgentDetail("+this.ID+",0)'><td>"+h+"<td>"+this.SellerName+"<td>"+this.BHK+"<td>"+this.Amount;e+="<td>"+this.Area+"<td>"+this.Bathroom+"<td>"+this.FloorNo+"<td style='max-width:180px;'>"+this.Facing+"<td>"+this.AvailableFrom+
"<td>"+this.PostedOnDate;h++}});e+="</table>";$("#divDetails").html(e);$("#divDetails table").HighLightRows();$("#divDetails table tr").css("cursor","pointer");$("#divDetails table th").addClass("tablehead")}
function ShowSocietyDetail(g){$.ajax({url:"Data.aspx?Action=GetSocietyDetail&Data1="+g,async:false,cache:false,success:function(e){e=ShowError2(e);$(e).each(function(){SocietyDetail.length=0;SocietyDetail.push({SocietyName:this[0],Address:this[1],Pin:this[2],City:this[3],BuiltYear:this[4],Country:this[5],Airport:this[6],Rail:this[7],Bus:this[8],School:this[9],Hospital:this[10],School:this[11],Shoping:this[12],PowerBack:this[13],Lat:this[14],Lng:this[15]})})}});var h="<table cellpadding='0' cellspacing ='1'>";
$(SocietyDetail).each(function(){h+="<tr><td>SocietyName<td>"+this.SocietyName;h+="<tr><td>Address<td>"+this.Address;h+="<tr><td>Pin<td>"+this.Pin;h+="<tr><td>City<td>"+this.City;h+="<tr><td>BuiltYear<td>"+this.BuiltYear;h+="<tr><td>Country<td>"+this.Country;h+="<tr><td>Airport<td>"+this.Airport;h+="<tr><td>Rail<td>"+this.Rail;h+="<tr><td>Bus<td>"+this.Bus;h+="<tr><td>Hospital<td>"+this.Hospital;h+="<tr><td>Shoping<td>"+this.Shoping;h+="<tr><td>PowerBack<td>"+(this.PowerBack!=0)?"Yes":"No";h+="<tr><td><td><span><a href='#' onclick='ShowMap("+
this.Lat+","+this.Lng+")'>Map</a></span> | <span><a  id='gal' href='#' onclick='ShowImageGalary(this,"+g+")'>Image Galary<a></span>"});h+="</tr></table>";$("#divSocietyDetail").html(h);return false}function ShowMap(g,h){$.fancybox({width:744,height:500,autoScale:false,scrolling:"yes",transitionIn:"elastic",transitionOut:"none",type:"iframe",href:"Map.htm?type=1&Lat="+g+"&Lng="+h})}
function ShowAgentDetail(g){$.ajax({url:"Data.aspx?Action=GetAgentDetail&Data1="+g+"&Data2=1",cache:false,success:function(h){$("#divAgentDetail").html(ShowError(h)[1])}});return false}function ShowPropertyDetail(g){$.ajax({url:"Data.aspx?Action=GetAvailabilityDetail&Data1="+g,cache:false,success:ShowDialog});return false}function ShowDialog(g){$("#dialog").dialog("open");$("#dialog").dialog("option","title","Society Details");$("#dialog").html(ShowError(g)[1])}
function GetAvlList(g){$.ajax({url:"Data.aspx?Action=GetAvailibilityText&Data4=1&Data3="+g+"&Data6="+sellerType,cache:false,success:function(h){h=ShowError2(h);$(h).each(function(){AvlList.push({ID:this[0],SocietyID:this[1],SocietyName:this[2],SellerID:this[3],SellerName:this[4],BHK:this[5],Amount:this[6],AvailableFrom:this[7],Area:this[8],Bathroom:this[9],FloorNo:this[10],Facing:this[11],PostedOnDate:this[12]})});ShowAvlList(AvlList)}})}
function ShowAvlList(g){var h=1,e="<table style='border-spacing:1px;'><tr><th></th><th>Society</th><th>BHK</th><th>Rent</th><th>Avl From</th><th>Area</th><th>Bath</th><th>Floor</th><th>Featutres</th><th>PostedOn</th></tr>";$(g).each(function(){if(this.ID!=undefined){e+="<tr  onclick='ShowAvailabilityDetail("+this.ID+","+this.SellerID+")'><td>"+h+"<td>"+this.SocietyName+"<td>"+this.BHK+"<td>"+this.Amount+"<td>"+this.AvailableFrom;e+="<td>"+this.Area+"<td>"+this.Bathroom+"<td>"+this.FloorNo+"<td>"+
this.Facing+"<td>"+this.PostedOnDate;e+="<tr><td><td colspan='9'><div id='divAvl"+this.ID+"'></div>";h++}});e+="</table>";$("#divAvlList").html(e);$("#divAvlList table").HighLightRows();$("#divAvlList table th").addClass("tablehead");GetClientList(SellerID)}
function GetClientList(g){ClentList.length=0;$.ajax({url:"Data.aspx?Action=GetClientList&Data1="+g,cache:false,success:function(h){h=ShowError2(h);$(h).each(function(){ClentList[this[0]]={ID:this[0],Name:this[1],Mobile:this[2],Email:this[3]}});ShowClientList(ClentList);GetAvlClientList(g)}})}
function GetAvlClientList(g){AvlClientList.length=0;$.ajax({url:"data.aspx?action=GetAvlClientList&Data5="+g,cache:false,success:function(h){h=ShowError2(h);$(h).each(function(){AvlClientList.push({AvlID:this[0],ClientID:this[1]})});UpdateAvlList()}})}
function UpdateAvlList(){$(AvlClientList).each(function(){var g=ClentList[this.ClientID];$("#divAvl"+this.AvlID).html($("#divAvl"+this.AvlID).html()+"<a href='#' style='margin-right:15px;' onclick='ShowClientDetail("+this.ClientID+","+this.AvlID+")'>"+g.Name+"</a>")})}
function ShowClientList(g){var h="<table id='clientList' style='border-spacing:1px;'><tr><th>ID</th><th>Name</th></tr>";$(g).each(function(){if(this.ID!=undefined)h+="<tr onclick='ShowClientDetail("+this.ID+")'><td>"+this.ID+"<td>"+this.Name});h+="</table>";$("#divClientList").html(h);$("#divClientList").HighLightRows();$("#divclientList table").css("min-width","200px");$("#divClientList table th").addClass("tablehead")}
function AssignClientToProperty(){$.ajax({url:"Data.aspx?Action=AssignClientToProperty&Data1="+avlID+"&Data2="+clientID+"&Data3="+(Connect?1:0),cache:false,success:function(){GetAvlList(SellerID)}})}function ShowAvailabilityDetail(g,h){avlID=g;clientID=0;$("#btnAsignAgent").hide();$("#frameEditAvailability")[0].src="Edit/EditAvailability.aspx?ID="+g;GetLatLng(h)}
function GetLatLng(g){$.ajax({url:"Data.aspx?Action=GetLatLng&Data1="+g,async:false,cache:false,success:function(h){var e=ShowError2(h);$(e).each(function(){var n=e[0];n=e[1];$("#frameMap")[0].src=BasePath+"Map.htm?type=1&Lat="+n+"&Lng="+lng})}})}
function ShowAvailabilityByClientID(g,h){var e=[],n=1,r="<table id='clientList' style='border-spacing:1px; width:300px;text-indent:0px;'><tr><th></th><th>Society</th><th>BHK</th><th>Rent</th><th>Area</th><th>Bath</th><th>FloorNo</th></tr>";if(h==0){$(AvlClientList).each(function(){this.ClientID==g&&e.push({ID:this.AvlID})});$(e).each(function(){var p=this.ID;$(AvlList).each(function(){if(this.ID==p){r+="<tr onclick='ShowAvailabilityDetail("+this.ID+")'><td>"+n+"</td><td>"+this.SocietyName+"</td><td>"+
this.BHK+"</td><td>"+this.Amount+"</td><td>"+this.Area+"</td><td>"+this.Bathroom+"</td><td>"+this.FloorNo+"</td>";n++}})})}else if(h==1){SellerID=0;$.ajax({url:"Data.aspx?Action=GetAsignClient&Data1="+ClientID,async:false,cache:false,success:function(p){p=ShowError2(p);$(p).each(function(){e.push({ID:this[1]})});var b=[];$(e).each(function(){$.ajax({url:"Data.aspx?Action=GetAvailabilityDetail&Data1="+this.ID,async:false,cache:false,success:function(D){D=ShowError2(D);$(D).each(function(){b.push({ID:this[0],
SocietyName:this[1],BHK:this[2],Amount:this[3],Area:this[4],Bathroom:this[5],FloorNo:this[6],SocietyID:this[7]})})}})});$(b).each(function(){r+="<tr onclick='ShowAvailabilityDetail("+this.ID+","+this.SocietyID+")'><td>"+n+"</td><td>"+this.SocietyName+"</td><td>"+this.BHK+"</td><td>"+this.Amount+"</td><td>"+this.Area+"</td><td>"+this.Bathroom+"</td><td>"+this.FloorNo+"</td>";n++})}})}r+="</tr></table>";$("#divClientAssignedAvl").html(r);$("#divClientAssignedAvl").HighLightRows();$("#divClientAssignedAvl th").css("background-color",
"#A9C7BC");$("#divClientAssignedAvl tr:hover").css("cursor","pointer")}function GetClietIDByMobileNo(g){$.ajax({url:"Data.aspx?Action=GetClietIDByMobileNo&Data1="+g,cache:false,success:function(h){ClientID=ShowError2(h);ShowAvailabilityByClientID(ClientID,1);$(".hd").show()}})}var Connect=false;
function ShowClientDetail(g,h){ShowAvailabilityByClientID(g,0);clientID=g;$("#btnAsignAgent").show();Connect=true;$("#btnAsignAgent").val("Asign To This Client");$("#frameClientDetail")[0].src=BasePath+"Edit/EditAgentClient.aspx?AgentID=510&ClientID="+g+"&AvlID="+avlID;if(g!=0&&h!=undefined){avlID=h;$("#btnAsignAgent").show();$("#btnAsignAgent").val("Remove");Connect=false}}
function UpdateBasePath(){$("img").each(function(){$(this).attr("src")&&$(this).attr("src").indexOf(BasePath)==-1&&$(this).attr("src").indexOf("http")==-1&&$(this).attr("src",BasePath+$(this).attr("src"))});$("a").each(function(){$(this).attr("href")&&$(this).attr("href").indexOf(BasePath)==-1&&$(this).attr("href").indexOf("http")!=0&&$(this).attr("href").indexOf("#")!=0&&$(this).data("nohrefupdate")==undefined&&$(this).attr("href",BasePath+$(this).attr("href"))})}
function ShowLanMark(g,h){alert(g+"|"+h);$("#frameMap")[0].contentWindow.ShowMarker(g,h)}function openSocietyEdit(g){$("#EditDialog").dialog({width:350,height:900,autoOpen:false,show:"fade",hide:"fade"});$("#EditDialog").dialog("open");$("#editframe").attr("src","Edit/EditSociety.aspx?ID="+g);$("#editframe").css({width:$("#EditDialog").outerWidth()-50,height:$("#EditDialog").outerHeight()-20})}
function openFloorPlanEdit(g){$("#EditDialog").dialog({width:450,height:900,autoOpen:false,show:"fade",hide:"fade"});$("#EditDialog").dialog("open");$("#editframe").attr("src","Edit/EditApartmentType.aspx?SocietyID="+g);$("#editframe").css({width:$("#EditDialog").outerWidth()-30,height:$("#EditDialog").outerHeight()-20})}function FindAddress(g){$("#frameMap2")[0].contentWindow.FindAddress(g)}function SetCenter(g,h){$("#frameMap2")[0].contentWindow.SetCenter(g,h)}
function UpdateLatLng(g,h){$("#frameEditSociety")[0].contentWindow.UpdateLatLng(g,h)}function ShowMap(g){$("#frameMap2")[0].src=BasePath+"Map.htm?"+g;$("#DivDialog").dialog({width:800,height:600,autoOpen:false,show:"fade",hide:"fade"});$("#DivDialog").dialog("open")}function AddToFav(g,h,e){var n=$("#hidField").val(),r=n.split("-")[0];n=n.split("-")[1];AddToMyList(r,n,g,h,e);ShowHistory()}
(function(g,h,e,n){var r=e(g),p=e(h),b=e.fancybox=function(){b.open.apply(this,arguments)},D=navigator.userAgent.match(/msie/),I=null,u=h.createTouch!==n,F=function(a){return a&&a.hasOwnProperty&&a instanceof e},x=function(a){return a&&"string"===e.type(a)},E=function(a){return x(a)&&0<a.indexOf("%")},o=function(a,d){var f=parseInt(a,10)||0;d&&E(a)&&(f*=b.getViewport()[d]/100);return Math.ceil(f)},v=function(a,d){return o(a,d)+"px"};e.extend(b,{version:"2.1.4",defaults:{padding:15,margin:20,width:800,
height:600,minWidth:100,minHeight:100,maxWidth:9999,maxHeight:9999,autoSize:true,autoHeight:false,autoWidth:false,autoResize:true,autoCenter:!u,fitToView:true,aspectRatio:false,topRatio:0.5,leftRatio:0.5,scrolling:"auto",wrapCSS:"",arrows:true,closeBtn:true,closeClick:false,nextClick:false,mouseWheel:true,autoPlay:false,playSpeed:3E3,preload:3,modal:false,loop:true,ajax:{dataType:"html",headers:{"X-fancyBox":true}},iframe:{scrolling:"auto",preload:true},swf:{wmode:"transparent",allowfullscreen:"true",
allowscriptaccess:"always"},keys:{next:{13:"left",34:"up",39:"left",40:"up"},prev:{8:"right",33:"down",37:"right",38:"down"},close:[27],play:[32],toggle:[70]},direction:{next:"left",prev:"right"},scrollOutside:true,index:0,type:null,href:null,content:null,title:null,tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1"><div class="fancybox-skin"><div class="fancybox-outer"><div class="fancybox-inner"></div></div></div></div>',image:'<img class="fancybox-image" src="{href}" alt="" />',iframe:'<iframe id="fancybox-frame{rnd}" name="fancybox-frame{rnd}" class="fancybox-iframe" frameborder="0" vspace="0" hspace="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen'+
(D?' allowtransparency="true"':"")+"></iframe>",error:'<p class="fancybox-error">The requested content cannot be loaded.<br/>Please try again later.</p>',closeBtn:'<a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a>',next:'<a title="Next" class="fancybox-nav fancybox-next" href="javascript:;"><span></span></a>',prev:'<a title="Previous" class="fancybox-nav fancybox-prev" href="javascript:;"><span></span></a>'},openEffect:"fade",openSpeed:250,openEasing:"swing",openOpacity:true,
openMethod:"zoomIn",closeEffect:"fade",closeSpeed:250,closeEasing:"swing",closeOpacity:true,closeMethod:"zoomOut",nextEffect:"elastic",nextSpeed:250,nextEasing:"swing",nextMethod:"changeIn",prevEffect:"elastic",prevSpeed:250,prevEasing:"swing",prevMethod:"changeOut",helpers:{overlay:true,title:true},onCancel:e.noop,beforeLoad:e.noop,afterLoad:e.noop,beforeShow:e.noop,afterShow:e.noop,beforeChange:e.noop,beforeClose:e.noop,afterClose:e.noop},group:{},opts:{},previous:null,coming:null,current:null,
isActive:false,isOpen:false,isOpened:false,wrap:null,skin:null,outer:null,inner:null,player:{timer:null,isActive:false},ajaxLoad:null,imgPreload:null,transitions:{},helpers:{},open:function(a,d){if(a&&(e.isPlainObject(d)||(d={}),false!==b.close(true)))return e.isArray(a)||(a=F(a)?e(a).get():[a]),e.each(a,function(f,c){var i={},j,k,l,m,q;"object"===e.type(c)&&(c.nodeType&&(c=e(c)),F(c)?(i={href:c.data("fancybox-href")||c.attr("href"),title:c.data("fancybox-title")||c.attr("title"),isDom:true,element:c},
e.metadata&&e.extend(true,i,c.metadata())):i=c);j=d.href||i.href||(x(c)?c:null);k=d.title!==n?d.title:i.title||"";m=(l=d.content||i.content)?"html":d.type||i.type;!m&&i.isDom&&(m=c.data("fancybox-type"),m||(m=(m=c.prop("class").match(/fancybox\.(\w+)/))?m[1]:null));x(j)&&(m||(b.isImage(j)?m="image":b.isSWF(j)?m="swf":"#"===j.charAt(0)?m="inline":x(c)&&(m="html",l=c)),"ajax"===m&&(q=j.split(/\s+/,2),j=q.shift(),q=q.shift()));l||("inline"===m?j?l=e(x(j)?j.replace(/.*(?=#[^\s]+$)/,""):j):i.isDom&&(l=
c):"html"===m?l=j:!m&&!j&&i.isDom&&(m="inline",l=c));e.extend(i,{href:j,type:m,content:l,title:k,selector:q});a[f]=i}),b.opts=e.extend(true,{},b.defaults,d),d.keys!==n&&(b.opts.keys=d.keys?e.extend({},b.defaults.keys,d.keys):false),b.group=a,b._start(b.opts.index)},cancel:function(){var a=b.coming;a&&false!==b.trigger("onCancel")&&(b.hideLoading(),b.ajaxLoad&&b.ajaxLoad.abort(),b.ajaxLoad=null,b.imgPreload&&(b.imgPreload.onload=b.imgPreload.onerror=null),a.wrap&&a.wrap.stop(true,true).trigger("onReset").remove(),
b.coming=null,b.current||b._afterZoomOut(a))},close:function(a){b.cancel();false!==b.trigger("beforeClose")&&(b.unbindEvents(),b.isActive&&(!b.isOpen||true===a?(e(".fancybox-wrap").stop(true).trigger("onReset").remove(),b._afterZoomOut()):(b.isOpen=b.isOpened=false,b.isClosing=true,e(".fancybox-item, .fancybox-nav").remove(),b.wrap.stop(true,true).removeClass("fancybox-opened"),b.transitions[b.current.closeMethod]())))},play:function(a){var d=function(){clearTimeout(b.player.timer)},f=function(){d();
b.current&&b.player.isActive&&(b.player.timer=setTimeout(b.next,b.current.playSpeed))},c=function(){d();e("body").unbind(".player");b.player.isActive=false;b.trigger("onPlayEnd")};if(true===a||!b.player.isActive&&false!==a){if(b.current&&(b.current.loop||b.current.index<b.group.length-1)){b.player.isActive=true;e("body").bind({"afterShow.player onUpdate.player":f,"onCancel.player beforeClose.player":c,"beforeLoad.player":d});f();b.trigger("onPlayStart")}}else c()},next:function(a){var d=b.current;
d&&(x(a)||(a=d.direction.next),b.jumpto(d.index+1,a,"next"))},prev:function(a){var d=b.current;d&&(x(a)||(a=d.direction.prev),b.jumpto(d.index-1,a,"prev"))},jumpto:function(a,d,f){var c=b.current;c&&(a=o(a),b.direction=d||c.direction[a>=c.index?"next":"prev"],b.router=f||"jumpto",c.loop&&(0>a&&(a=c.group.length+a%c.group.length),a%=c.group.length),c.group[a]!==n&&(b.cancel(),b._start(a)))},reposition:function(a,d){var f=b.current,c=f?f.wrap:null,i;c&&(i=b._getPosition(d),a&&"scroll"===a.type?(delete i.position,
c.stop(true,true).animate(i,200)):(c.css(i),f.pos=e.extend({},f.dim,i)))},update:function(a){var d=a&&a.type,f=!d||"orientationchange"===d;f&&(clearTimeout(I),I=null);b.isOpen&&!I&&(I=setTimeout(function(){var c=b.current;c&&!b.isClosing&&(b.wrap.removeClass("fancybox-tmp"),(f||"load"===d||"resize"===d&&c.autoResize)&&b._setDimension(),"scroll"===d&&c.canShrink||b.reposition(a),b.trigger("onUpdate"),I=null)},f&&!u?0:300))},toggle:function(a){b.isOpen&&(b.current.fitToView="boolean"===e.type(a)?a:
!b.current.fitToView,u&&(b.wrap.removeAttr("style").addClass("fancybox-tmp"),b.trigger("onUpdate")),b.update())},hideLoading:function(){p.unbind(".loading");e("#fancybox-loading").remove()},showLoading:function(){var a,d;b.hideLoading();a=e('<div id="fancybox-loading"><div></div></div>').click(b.cancel).appendTo("body");p.bind("keydown.loading",function(f){if(27===(f.which||f.keyCode)){f.preventDefault();b.cancel()}});b.defaults.fixed||(d=b.getViewport(),a.css({position:"absolute",top:0.5*d.h+d.y,
left:0.5*d.w+d.x}))},getViewport:function(){var a=b.current&&b.current.locked||false,d={x:r.scrollLeft(),y:r.scrollTop()};a?(d.w=a[0].clientWidth,d.h=a[0].clientHeight):(d.w=u&&g.innerWidth?g.innerWidth:r.width(),d.h=u&&g.innerHeight?g.innerHeight:r.height());return d},unbindEvents:function(){b.wrap&&F(b.wrap)&&b.wrap.unbind(".fb");p.unbind(".fb");r.unbind(".fb")},bindEvents:function(){var a=b.current,d;a&&(r.bind("orientationchange.fb"+(u?"":" resize.fb")+(a.autoCenter&&!a.locked?" scroll.fb":""),
b.update),(d=a.keys)&&p.bind("keydown.fb",function(f){var c=f.which||f.keyCode,i=f.target||f.srcElement;if(27===c&&b.coming)return false;!f.ctrlKey&&!f.altKey&&!f.shiftKey&&!f.metaKey&&(!i||!i.type&&!e(i).is("[contenteditable]"))&&e.each(d,function(j,k){if(1<a.group.length&&k[c]!==n)return b[j](k[c]),f.preventDefault(),false;if(-1<e.inArray(c,k))return b[j](),f.preventDefault(),false})}),e.fn.mousewheel&&a.mouseWheel&&b.wrap.bind("mousewheel.fb",function(f,c,i,j){for(var k=e(f.target||null),l=false;k.length&&
!l&&!k.is(".fancybox-skin")&&!k.is(".fancybox-wrap");){l=k[0]&&!(k[0].style.overflow&&"hidden"===k[0].style.overflow)&&(k[0].clientWidth&&k[0].scrollWidth>k[0].clientWidth||k[0].clientHeight&&k[0].scrollHeight>k[0].clientHeight);k=e(k).parent()}if(0!==c&&!l&&1<b.group.length&&!a.canShrink){if(0<j||0<i)b.prev(0<j?"down":"left");else if(0>j||0>i)b.next(0>j?"up":"right");f.preventDefault()}}))},trigger:function(a,d){var f,c=d||b.coming||b.current;if(c){e.isFunction(c[a])&&(f=c[a].apply(c,Array.prototype.slice.call(arguments,
1)));if(false===f)return false;c.helpers&&e.each(c.helpers,function(i,j){j&&b.helpers[i]&&e.isFunction(b.helpers[i][a])&&(j=e.extend(true,{},b.helpers[i].defaults,j),b.helpers[i][a](j,c))});e.event.trigger(a+".fb")}},isImage:function(a){return x(a)&&a.match(/(^data:image\/.*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp)((\?|#).*)?$)/i)},isSWF:function(a){return x(a)&&a.match(/\.(swf)((\?|#).*)?$/i)},_start:function(a){var d={},f,c;a=o(a);f=b.group[a]||null;if(!f)return false;d=e.extend(true,{},b.opts,f);f=d.margin;
c=d.padding;"number"===e.type(f)&&(d.margin=[f,f,f,f]);"number"===e.type(c)&&(d.padding=[c,c,c,c]);d.modal&&e.extend(true,d,{closeBtn:false,closeClick:false,nextClick:false,arrows:false,mouseWheel:false,keys:null,helpers:{overlay:{closeClick:false}}});d.autoSize&&(d.autoWidth=d.autoHeight=true);"auto"===d.width&&(d.autoWidth=true);"auto"===d.height&&(d.autoHeight=true);d.group=b.group;d.index=a;b.coming=d;if(false===b.trigger("beforeLoad"))b.coming=null;else{c=d.type;f=d.href;if(!c)return b.coming=
null,b.current&&b.router&&"jumpto"!==b.router?(b.current.index=a,b[b.router](b.direction)):false;b.isActive=true;if("image"===c||"swf"===c){d.autoHeight=d.autoWidth=false;d.scrolling="visible"}"image"===c&&(d.aspectRatio=true);"iframe"===c&&u&&(d.scrolling="scroll");d.wrap=e(d.tpl.wrap).addClass("fancybox-"+(u?"mobile":"desktop")+" fancybox-type-"+c+" fancybox-tmp "+d.wrapCSS).appendTo(d.parent||"body");e.extend(d,{skin:e(".fancybox-skin",d.wrap),outer:e(".fancybox-outer",d.wrap),inner:e(".fancybox-inner",
d.wrap)});e.each(["Top","Right","Bottom","Left"],function(i,j){d.skin.css("padding"+j,v(d.padding[i]))});b.trigger("onReady");if("inline"===c||"html"===c){if(!d.content||!d.content.length)return b._error("content")}else if(!f)return b._error("href");"image"===c?b._loadImage():"ajax"===c?b._loadAjax():"iframe"===c?b._loadIframe():b._afterLoad()}},_error:function(a){e.extend(b.coming,{type:"html",autoWidth:true,autoHeight:true,minWidth:0,minHeight:0,scrolling:"no",hasError:a,content:b.coming.tpl.error});
b._afterLoad()},_loadImage:function(){var a=b.imgPreload=new Image;a.onload=function(){this.onload=this.onerror=null;b.coming.width=this.width;b.coming.height=this.height;b._afterLoad()};a.onerror=function(){this.onload=this.onerror=null;b._error("image")};a.src=b.coming.href;true!==a.complete&&b.showLoading()},_loadAjax:function(){var a=b.coming;b.showLoading();b.ajaxLoad=e.ajax(e.extend({},a.ajax,{url:a.href,error:function(d,f){b.coming&&"abort"!==f?b._error("ajax",d):b.hideLoading()},success:function(d,
f){"success"===f&&(a.content=d,b._afterLoad())}}))},_loadIframe:function(){var a=b.coming,d=e(a.tpl.iframe.replace(/\{rnd\}/g,(new Date).getTime())).attr("scrolling",u?"auto":a.iframe.scrolling).attr("src",a.href);e(a.wrap).bind("onReset",function(){try{e(this).find("iframe").hide().attr("src","//about:blank").end().empty()}catch(f){}});a.iframe.preload&&(b.showLoading(),d.one("load",function(){e(this).data("ready",1);u||e(this).bind("load.fb",b.update);e(this).parents(".fancybox-wrap").width("100%").removeClass("fancybox-tmp").show();
b._afterLoad()}));a.content=d.appendTo(a.inner);a.iframe.preload||b._afterLoad()},_preloadImages:function(){var a=b.group,d=b.current,f=a.length,c=d.preload?Math.min(d.preload,f-1):0,i,j;for(j=1;j<=c;j+=1){i=a[(d.index+j)%f];"image"===i.type&&i.href&&((new Image).src=i.href)}},_afterLoad:function(){var a=b.coming,d=b.current,f,c,i,j,k;b.hideLoading();if(a&&false!==b.isActive)if(false===b.trigger("afterLoad",a,d)){a.wrap.stop(true).trigger("onReset").remove();b.coming=null}else{d&&(b.trigger("beforeChange",
d),d.wrap.stop(true).removeClass("fancybox-opened").find(".fancybox-item, .fancybox-nav").remove());b.unbindEvents();f=a.content;c=a.type;i=a.scrolling;e.extend(b,{wrap:a.wrap,skin:a.skin,outer:a.outer,inner:a.inner,current:a,previous:d});j=a.href;switch(c){case "inline":case "ajax":case "html":a.selector?f=e("<div>").html(f).find(a.selector):F(f)&&(f.data("fancybox-placeholder")||f.data("fancybox-placeholder",e('<div class="fancybox-placeholder"></div>').insertAfter(f).hide()),f=f.show().detach(),
a.wrap.bind("onReset",function(){e(this).find(f).length&&f.hide().replaceAll(f.data("fancybox-placeholder")).data("fancybox-placeholder",false)}));break;case "image":f=a.tpl.image.replace("{href}",j);break;case "swf":f='<object id="fancybox-swf" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="100%" height="100%"><param name="movie" value="'+j+'"></param>';k="";e.each(a.swf,function(l,m){f+='<param name="'+l+'" value="'+m+'"></param>';k+=" "+l+'="'+m+'"'});f+='<embed src="'+j+'" type="application/x-shockwave-flash" width="100%" height="100%"'+
k+"></embed></object>"}(!F(f)||!f.parent().is(a.inner))&&a.inner.append(f);b.trigger("beforeShow");a.inner.css("overflow","yes"===i?"scroll":"no"===i?"hidden":i);b._setDimension();b.reposition();b.isOpen=false;b.coming=null;b.bindEvents();if(b.isOpened)d.prevMethod&&b.transitions[d.prevMethod]();else e(".fancybox-wrap").not(a.wrap).stop(true).trigger("onReset").remove();b.transitions[b.isOpened?a.nextMethod:a.openMethod]();b._preloadImages()}},_setDimension:function(){var a=b.getViewport(),d=0,f=
false,c=false;f=b.wrap;var i=b.skin,j=b.inner,k=b.current;c=k.width;var l=k.height,m=k.minWidth,q=k.minHeight,s=k.maxWidth,t=k.maxHeight,O=k.scrolling,L=k.scrollOutside?k.scrollbarWidth:0,w=k.margin,y=o(w[1]+w[3]),G=o(w[0]+w[2]),M,z,J,B,A,H,N,C,K;f.add(i).add(j).width("auto").height("auto").removeClass("fancybox-tmp");w=o(i.outerWidth(true)-i.width());M=o(i.outerHeight(true)-i.height());z=y+w;J=G+M;B=E(c)?(a.w-z)*o(c)/100:c;A=E(l)?(a.h-J)*o(l)/100:l;if("iframe"===k.type){if(K=k.content,k.autoHeight&&
1===K.data("ready"))try{K[0].contentWindow.document.location&&(j.width(B).height(9999),H=K.contents().find("body"),L&&H.css("overflow-x","hidden"),A=H.height())}catch(P){}}else if(k.autoWidth||k.autoHeight){j.addClass("fancybox-tmp");k.autoWidth||j.width(B);k.autoHeight||j.height(A);k.autoWidth&&(B=j.width());k.autoHeight&&(A=j.height());j.removeClass("fancybox-tmp")}c=o(B);l=o(A);C=B/A;m=o(E(m)?o(m,"w")-z:m);s=o(E(s)?o(s,"w")-z:s);q=o(E(q)?o(q,"h")-J:q);t=o(E(t)?o(t,"h")-J:t);H=s;N=t;k.fitToView&&
(s=Math.min(a.w-z,s),t=Math.min(a.h-J,t));z=a.w-y;G=a.h-G;k.aspectRatio?(c>s&&(c=s,l=o(c/C)),l>t&&(l=t,c=o(l*C)),c<m&&(c=m,l=o(c/C)),l<q&&(l=q,c=o(l*C))):(c=Math.max(m,Math.min(c,s)),k.autoHeight&&"iframe"!==k.type&&(j.width(c),l=j.height()),l=Math.max(q,Math.min(l,t)));if(k.fitToView)if(j.width(c).height(l),f.width(c+w),a=f.width(),y=f.height(),k.aspectRatio)for(;(a>z||y>G)&&c>m&&l>q&&!(19<d++);){l=Math.max(q,Math.min(t,l-10));c=o(l*C);c<m&&(c=m,l=o(c/C));c>s&&(c=s,l=o(c/C));j.width(c).height(l);
f.width(c+w);a=f.width();y=f.height()}else{c=Math.max(m,Math.min(c,c-(a-z)));l=Math.max(q,Math.min(l,l-(y-G)))}L&&"auto"===O&&l<A&&c+w+L<z&&(c+=L);j.width(c).height(l);f.width(c+w);a=f.width();y=f.height();f=(a>z||y>G)&&c>m&&l>q;c=k.aspectRatio?c<H&&l<N&&c<B&&l<A:(c<H||l<N)&&(c<B||l<A);e.extend(k,{dim:{width:v(a),height:v(y)},origWidth:B,origHeight:A,canShrink:f,canExpand:c,wPadding:w,hPadding:M,wrapSpace:y-i.outerHeight(true),skinSpace:i.height()-l});!K&&k.autoHeight&&l>q&&l<t&&!c&&j.height("auto")},
_getPosition:function(a){var d=b.current,f=b.getViewport(),c=d.margin,i=b.wrap.width()+c[1]+c[3],j=b.wrap.height()+c[0]+c[2];c={position:"absolute",top:c[0],left:c[3]};d.autoCenter&&d.fixed&&!a&&j<=f.h&&i<=f.w?c.position="fixed":d.locked||(c.top+=f.y,c.left+=f.x);c.top=v(Math.max(c.top,c.top+(f.h-j)*d.topRatio));c.left=v(Math.max(c.left,c.left+(f.w-i)*d.leftRatio));return c},_afterZoomIn:function(){var a=b.current;a&&(b.isOpen=b.isOpened=true,b.wrap.css("overflow","visible").addClass("fancybox-opened"),
b.update(),(a.closeClick||a.nextClick&&1<b.group.length)&&b.inner.css("cursor","pointer").bind("click.fb",function(d){!e(d.target).is("a")&&!e(d.target).parent().is("a")&&(d.preventDefault(),b[a.closeClick?"close":"next"]())}),a.closeBtn&&e(a.tpl.closeBtn).appendTo(b.skin).bind("click.fb",function(d){d.preventDefault();b.close()}),a.arrows&&1<b.group.length&&((a.loop||0<a.index)&&e(a.tpl.prev).appendTo(b.outer).bind("click.fb",b.prev),(a.loop||a.index<b.group.length-1)&&e(a.tpl.next).appendTo(b.outer).bind("click.fb",
b.next)),b.trigger("afterShow"),!a.loop&&a.index===a.group.length-1?b.play(false):b.opts.autoPlay&&!b.player.isActive&&(b.opts.autoPlay=false,b.play()))},_afterZoomOut:function(a){a=a||b.current;e(".fancybox-wrap").trigger("onReset").remove();e.extend(b,{group:{},opts:{},router:false,current:null,isActive:false,isOpened:false,isOpen:false,isClosing:false,wrap:null,skin:null,outer:null,inner:null});b.trigger("afterClose",a)}});b.transitions={getOrigPosition:function(){var a=b.current,d=a.element,f=
a.orig,c={},i=50,j=50,k=a.hPadding,l=a.wPadding,m=b.getViewport();!f&&a.isDom&&d.is(":visible")&&(f=d.find("img:first"),f.length||(f=d));F(f)?(c=f.offset(),f.is("img")&&(i=f.outerWidth(),j=f.outerHeight())):(c.top=m.y+(m.h-j)*a.topRatio,c.left=m.x+(m.w-i)*a.leftRatio);if("fixed"===b.wrap.css("position")||a.locked){c.top-=m.y;c.left-=m.x}return{top:v(c.top-k*a.topRatio),left:v(c.left-l*a.leftRatio),width:v(i+l),height:v(j+k)}},step:function(a,d){var f,c,i=d.prop;c=b.current;var j=c.wrapSpace,k=c.skinSpace;
if("width"===i||"height"===i){f=d.end===d.start?1:(a-d.start)/(d.end-d.start);b.isClosing&&(f=1-f);c="width"===i?c.wPadding:c.hPadding;c=a-c;b.skin[i](o("width"===i?c:c-j*f));b.inner[i](o("width"===i?c:c-j*f-k*f))}},zoomIn:function(){var a=b.current,d=a.pos,f=a.openEffect,c="elastic"===f,i=e.extend({opacity:1},d);delete i.position;c?(d=this.getOrigPosition(),a.openOpacity&&(d.opacity=0.1)):"fade"===f&&(d.opacity=0.1);b.wrap.css(d).animate(i,{duration:"none"===f?0:a.openSpeed,easing:a.openEasing,step:c?
this.step:null,complete:b._afterZoomIn})},zoomOut:function(){var a=b.current,d=a.closeEffect,f="elastic"===d,c={opacity:0.1};f&&(c=this.getOrigPosition(),a.closeOpacity&&(c.opacity=0.1));b.wrap.animate(c,{duration:"none"===d?0:a.closeSpeed,easing:a.closeEasing,step:f?this.step:null,complete:b._afterZoomOut})},changeIn:function(){var a=b.current,d=a.nextEffect,f=a.pos,c={opacity:1},i=b.direction,j;f.opacity=0.1;"elastic"===d&&(j="down"===i||"up"===i?"top":"left","down"===i||"right"===i?(f[j]=v(o(f[j])-
200),c[j]="+=200px"):(f[j]=v(o(f[j])+200),c[j]="-=200px"));"none"===d?b._afterZoomIn():b.wrap.css(f).animate(c,{duration:a.nextSpeed,easing:a.nextEasing,complete:b._afterZoomIn})},changeOut:function(){var a=b.previous,d=a.prevEffect,f={opacity:0.1},c=b.direction;"elastic"===d&&(f["down"===c||"up"===c?"top":"left"]=("up"===c||"left"===c?"-":"+")+"=200px");a.wrap.animate(f,{duration:"none"===d?0:a.prevSpeed,easing:a.prevEasing,complete:function(){e(this).trigger("onReset").remove()}})}};b.helpers.overlay=
{defaults:{closeClick:true,speedOut:200,showEarly:true,css:{},locked:!u,fixed:true},overlay:null,fixed:false,create:function(a){a=e.extend({},this.defaults,a);this.overlay&&this.close();this.overlay=e('<div class="fancybox-overlay"></div>').appendTo("body");this.fixed=false;a.fixed&&b.defaults.fixed&&(this.overlay.addClass("fancybox-overlay-fixed"),this.fixed=true)},open:function(a){var d=this;a=e.extend({},this.defaults,a);this.overlay?this.overlay.unbind(".overlay").width("auto").height("auto"):
this.create(a);this.fixed||(r.bind("resize.overlay",e.proxy(this.update,this)),this.update());a.closeClick&&this.overlay.bind("click.overlay",function(f){e(f.target).hasClass("fancybox-overlay")&&(b.isActive?b.close():d.close())});this.overlay.css(a.css).show()},close:function(){e(".fancybox-overlay").remove();r.unbind("resize.overlay");this.overlay=null;false!==this.margin&&(e("body").css("margin-right",this.margin),this.margin=false);this.el&&this.el.removeClass("fancybox-lock")},update:function(){var a=
"100%",d;this.overlay.width(a).height("100%");D?(d=Math.max(h.documentElement.offsetWidth,h.body.offsetWidth),p.width()>d&&(a=p.width())):p.width()>r.width()&&(a=p.width());this.overlay.width(a).height(p.height())},onReady:function(a,d){e(".fancybox-overlay").stop(true,true);this.overlay||(this.margin=p.height()>r.height()||"scroll"===e("body").css("overflow-y")?e("body").css("margin-right"):false,this.el=h.all&&!h.querySelector?e("html"):e("body"),this.create(a));a.locked&&this.fixed&&(d.locked=
this.overlay.append(d.wrap),d.fixed=false);true===a.showEarly&&this.beforeShow.apply(this,arguments)},beforeShow:function(a,d){d.locked&&(this.el.addClass("fancybox-lock"),false!==this.margin&&e("body").css("margin-right",o(this.margin)+d.scrollbarWidth));this.open(a)},onUpdate:function(){this.fixed||this.update()},afterClose:function(a){this.overlay&&!b.isActive&&this.overlay.fadeOut(a.speedOut,e.proxy(this.close,this))}};b.helpers.title={defaults:{type:"float",position:"bottom"},beforeShow:function(a){var d=
b.current,f=d.title,c=a.type;e.isFunction(f)&&(f=f.call(d.element,d));if(x(f)&&""!==e.trim(f)){d=e('<div class="fancybox-title fancybox-title-'+c+'-wrap">'+f+"</div>");switch(c){case "inside":c=b.skin;break;case "outside":c=b.wrap;break;case "over":c=b.inner;break;default:c=b.skin;d.appendTo("body");D&&d.width(d.width());d.wrapInner('<span class="child"></span>');b.current.margin[2]+=Math.abs(o(d.css("margin-bottom")))}d["top"===a.position?"prependTo":"appendTo"](c)}}};e.fn.fancybox=function(a){var d,
f=e(this),c=this.selector||"",i=function(j){var k=e(this).blur(),l=d,m,q;!j.ctrlKey&&!j.altKey&&!j.shiftKey&&!j.metaKey&&!k.is(".fancybox-wrap")&&(m=a.groupAttr||"data-fancybox-group",q=k.attr(m),q||(m="rel",q=k.get(0)[m]),q&&""!==q&&"nofollow"!==q&&(c.length&&e(c),k=k.filter("["+m+'="'+q+'"]'),l=k.index(this)),a.index=l,false!==b.open(k,a)&&j.preventDefault())};a=a||{};d=a.index||0;!c||false===a.live?f.unbind("click.fb-start").bind("click.fb-start",i):p.undelegate(c,"click.fb-start").delegate(c+
":not('.fancybox-item, .fancybox-nav')","click.fb-start",i);this.filter("[data-fancybox-start=1]").trigger("click");return this};p.ready(function(){e.scrollbarWidth===n&&(e.scrollbarWidth=function(){var c=e('<div style="width:50px;height:50px;overflow:auto"><div/></div>').appendTo("body"),i=c.children();i=i.innerWidth()-i.height(99).innerWidth();c.remove();return i});if(e.support.fixedPosition===n){var a=e.support,d=e('<div style="position:fixed;top:20px;"></div>').appendTo("body"),f=20===d[0].offsetTop||
15===d[0].offsetTop;d.remove();a.fixedPosition=f}e.extend(b.defaults,{scrollbarWidth:e.scrollbarWidth(),fixed:e.support.fixedPosition,parent:e("body")})})})(window,document,jQuery);var CurrentPage="home";$(document).ready(function(){$("ul.nav li."+CurrentPage).addClass("active");$("ul.nav li."+CurrentPage+" i").removeClass("icon-inverse");$("ul.nav li."+CurrentPage+" i").addClass("icon-white");$("#txtMainSearh").keyup(GetSearchedList)});
function GetSearchedList(){txtVal=$("#txtMainSearh").val();txtVal.length==0?$("#divSearchedResult").hide():$.ajax({url:BasePath+"Data.aspx?Action=GlobalSearch&term="+txtVal,success:function(g){SearchResult=JSON.parse(g);$("#divSearchedResult").html(DisplaySearchedData());$("#divSearchedResult").show();$("#divSearchedResult").css({top:40,left:$("li.search").position().left()});$("#divSearchedResult").hover(function(){Is_Search_Box=true},function(){Is_Search_Box=false})}})}
function DisplaySearchedData(){var g="<table class='table table-bordered table-hover table-striped table-condensed'>";g+="<tr><th>Name<th>Area<th>City";$(SearchResult).each(function(){switch(this.type){case "C":g+="<tr><td><td><td><a href='"+BasePath+"city/"+this.label+"'>"+this.label+"</a>";break;case "P":var h=this.label.split(",");g+="<tr><td><a href='"+BasePath+"project/"+this.urlname+"'  onclick='' target='_blank'>"+h[0]+"</a><td>"+h[1]+"<td>"+h[2];break;case "B":g+="<tr><td><a href='"+BasePath+
"builder/"+this.urlname+"'  onclick='' target='_blank'>"+this.label+"</a><td><td>"}});return g+"</table>"}
$.fn.HighLightRows2=function(){var g=this;ResetRowColor1(g);$("tr",this).hover(function(){$(this).css({"background-color":"#17c8e1",color:"white"})},function(){$(this).css({"background-color":jQuery.data(this,"OldClr"),color:"black"})});$("tr",this).click(function(){ResetRowColor1(g);jQuery.data(this,"OldClr","#17c8e1");$(this).css("background-color","#17c8e1")});if(HignLightFirstRow){$(this).find("tr:eq(1)").trigger("click");HignLightFirstRow=false}};
function ResetRowColor1(g){$("tr",g).each(function(h){h=h%2==0?"white":"#dee6fe";$(this).css("background-color",h);jQuery.data(this,"OldClr",h)})}var HignLightFirstRow;
$.fn.HighLightRows=function(){var g=this;ResetRowColor(g);g.attr("id")=="tableContact"||g.attr("id")=="tableCompany"?$("tr",this).hover(function(){$(this).css("background-color","#D5D5D5")},function(){$(this).css("background-color",jQuery.data(this,"OldClr"))}):$("tr:gt(0)",this).hover(function(){$(this).css("background-color","rgba(4, 146, 248, 0.30)")},function(){$(this).css("background-color",jQuery.data(this,"OldClr"))});$("tr",this).click(function(){ResetRowColor(g);jQuery.data(this,"OldClr",
"#D5D5D5");$(this).css("background-color","#D5D5D5")});if(HignLightFirstRow){$(this).find("tr:eq(1)").trigger("click");HignLightFirstRow=false}};function ResetRowColor(g){$("tr",g).each(function(h){if(g.attr("id")=="tableContact"||g.attr("id")=="tableCompany"){h=h%2==0?"white":"whiteSmoke";$(this).css("background-color",h);jQuery.data(this,"OldClr",h)}else if(h!=0){h=h%2==0?"white":"whiteSmoke";$(this).css("background-color",h);jQuery.data(this,"OldClr",h)}})}
function ShowError(g){g=g.split("~");g[0]!=""&&alert("Error-"+g[0]);return g}function ShowError2(g){g=g.split("~");var h=[];if(g[0]!="")alert("Error-"+g[0]);else for(var e=1;e<g.length;e++)if(g[e]!=""){var n=g[e].split("^");h.push(n)}return h}function ListBoxFilter(g,h){var e=$(g).val().toLowerCase();$(h+" option").each(function(n){if($(this).text().toLowerCase().indexOf(e)==0)$(h).get(0).selectedIndex=n})}
function SaveInLocalStorage(g,h){if(typeof localStorage!="undefined"){window.localStorage.removeItem(g);window.localStorage.setItem(g,h);return true}else{alert("Your browser does not support local storage, please upgrade to latest browser");return false}}function LoadFromLocalStorage(g,h){var e;if(typeof window.localStorage!="undefined")e=window.localStorage.getItem(g);else throw"window.localStorage, not defined";return h&&!e?h:e}
function RemoveFromLocalStorage(g){window.localStorage.removeItem(g)}function ClearLocalStoreage(){if(typeof window.localStorage!="undefined")window.localStorage.clear();else throw"window.localStorage, not defined";}function ReadClientScript(){$.ajax({url:BasePath+"Data.aspx?Action=GetClientScript",cache:false,success:function(g){$.globalEval(g)}})}var reEscape=RegExp("(\\/|\\.|\\*|\\+|\\?|\\||\\(|\\)|\\[|\\]|\\{|\\}|\\\\)","g");
$.ui.autocomplete.prototype._renderItem=function(g,h){var e="#08c",n="Project";switch(h.type){case "P":e="#08c";n="Project";break;case "B":e="orange";n="Builder";break;case "":e="voilet";n="City"}var r="("+this.term.replace(reEscape,"\\$1")+")";e=h.label.replace(RegExp(r,"gi"),'<span style="font-weight:bold;">$1</span>')+"-<span style='color:"+e+"; font-style:italic;'>"+n+"</span>";return $("<li></li>").data("item.autocomplete",h).append("<a>"+e+"</a>").appendTo(g)};CurrentPage="Home";
$(document).ready(function(){var g=LoadFromLocalStorage("SelectedCity");if(g!=null&&$("#ddCity option:contains("+g+")").length&&$("#ddCity option:selected").text()!=g)location.href=BasePath+"city/"+g;$(window).scroll(function(){$(this).scrollTop()>100?$(".scrollup").fadeIn():$(".scrollup").fadeOut()});$(".scrollup").click(function(){$("html, body").animate({scrollTop:0},600);return false});$("#txtSearch").autocomplete({minLength:2,select:function(h,e){window.location=e.item.urlname},source:SendRequest})});
var cache={},lastXhr;function SendRequest(g,h){var e=g.term;if(e in cache)h(cache[e]);else lastXhr=$.getJSON(BasePath+"Data.aspx?Action=AllSearch&Data1=0",g,function(n,r,p){cache[e]=n;p===lastXhr&&h(n)})}function ShowProjects(){SaveInLocalStorage("SelectedCity",$("#ddCity option:selected").text());location.href=BasePath+"city/"+$("#ddCity option:selected").text().toLowerCase()}var FilterMinBudget=0,FilterMaxBudget=999999999,FilterBHK=0;
function SelectBudget(g,h,e){FilterMinBudget=g;FilterMaxBudget=h;$("#ltSelectedBudget").html("Budget "+$(e).html());UpdateProjectList()}function SelectBHK(g,h){FilterBHK=g;$("#ltSelectedBHK").html($(h).html());UpdateProjectList()}
function UpdateProjectList(){obj=$("table.ProjectListHome");$(obj).find("tr:gt(1)").remove();var g=0;$(ProjectList).each(function(){var h=false,e=[];$(this.Apts).each(function(p){if(!(p>4)){e[p]=[];$(this).each(function(){if(this.Price>=FilterMinBudget&&this.Price<=FilterMaxBudget){e[p].push(this);h=true}})}});var n=FilterBHK==0;$(e).each(function(){if(this.length>0&&this[0].BHK==FilterBHK)n=true});if(h&&n){g++;var r="<tr><td>"+g+"<td><div><a href='"+BasePath+"project/"+this.URLName+"'>"+this.Name+
"</a>";$(e).each(function(p){if(!(p<1))if(this.length>0){p=this[0].Area;var b=this[0].Price;if(this.length>1){if(this[this.length-1].Area!=p)p+="-"+this[this.length-1].Area;if(this[this.length-1].Price!=b)b+="-"+this[this.length-1].Price;if(b=="0")b="-"}r+="<td class='area'>"+p+"<td class='price'>"+b}else r+="<td><td>"});r+="<td><div>"+this.SubCity+"</div>";$("tr:last",obj).after(r)}});$("#footer").css("bottom","0");return false}
$(function(){$("#txtSearch").on("keyup",function(){var g=$(this).val().toUpperCase().trim();$(".ProjectListHome").css("display","none");$(".ProjectListHome tr").not(".skp").each(function(){$(this).css("display",$(this).text().toUpperCase().indexOf(g)>-1||g.length==0?"":"none")});$(".ProjectListHome").css("display","")})});$.fn.removeHighlight=function(){return this.find(".highlight").each(function(){with(this.parentNode){replaceChild(this.firstChild,this);normalize()}}).end()};
